name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Continuous Integration (CI)
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Assuming you have tests defined in your project

  # Step 2: Continuous Deployment (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures that tests pass before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Replace with the secret name for your EC2 SSH key

      - name: Deploy to EC2
        env:
          HOST: "your-ec2-ip-address"   # Replace with your EC2 IP
          USER: "ec2-user"              # Replace with your EC2 username (e.g., ubuntu or ec2-user)
        run: |
          # Copy files to EC2 instance
          scp -r . $USER@$HOST:/path/to/your
